routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::group(['namespace' => 'Frontend'], function () {
    Route::get('/', 'FrontendController@index')->name('home');
    Route::get('sing-up', 'AuthController@singUpFormShow')->name('sing-up');
    Route::get('login-form', 'AuthController@showLoginForm')->name('frontend.loginForm');
    Route::post('registration', 'AuthController@registrationProcess')
        ->name('frontend.registration');
    Route::post('login', 'AuthController@loginProcess')
        ->name('frontend.login');
    Route::get('/track-finds', 'ParcelTrackerController@track')->name('parcel.find');
    Route::get('/track-parcels', 'ParcelTrackerController@trackParcel')->name('parcel.track');
    Route::group(['middleware' => 'FrontendAuth'], static function () {
        Route::post('profile/update', 'AuthController@update')->name('profile.update');
        Route::post('password/change', 'AuthController@passwordChange')->name('passwordChange');
        Route::get('dashboard', 'DashboardController@index')->name('frontend.dashboard');
        Route::get('dashboard/shipping', 'DashboardController@shipping')->name('frontend.shipping');
        Route::get('logout', 'AuthController@logout')->name('frontend.logout');
        Route::post('send-request', 'OrderController@store')->name('frontend.request');
    });
});


Route::group(['prefix' => 'admin', 'namespace' => 'Backend'], static function () {
    Route::post('/login', 'AuthController@loginProcess')->name('login');
    Route::get('/', 'UsersController@login')->name('users.login');
    Route::group(['middleware' => ['auth','RoleCheck']], static function () {
        Route::get('dashboard', 'DashboardController@index')->name('dashboard.index');
        Route::get('/logout', 'AuthController@logout')->name('logout');
        Route::get('/users', 'UsersController@index')->name('users.index');
        Route::get('/users/edit/{id}', 'UsersController@edit')->name('users.edit');
        Route::post('/users/update/{id}', 'UsersController@update')->name('users.update');
        Route::get('/users/{id}/delete', 'UsersController@delete')->name('users.delete');
        Route::get('/users/create', 'UsersController@create')->name('users.create');
        Route::post('/users/store', 'UsersController@store')->name('users.store');
        Route::get('/empolyee/list', 'UsersController@empolyeList')->name('employee.list');
        Route::get('/empolyee/create', 'UsersController@employeeCreate')->name('employee.create');
        Route::post('/empolyee/create', 'UsersController@employeeStore')->name('employee.create');
        Route::get('/customer/list', 'UsersController@customerList')->name('customer.list');
        Route::get('/customer/create', 'UsersController@customerCreate')->name('customer.create');

        Route::get('product-types', 'ProductTypeController@index')->name('productTypes.index');
        Route::get('product-types/create', 'ProductTypeController@create')->name('productTypes.create');
        Route::post('product-types/store', 'ProductTypeController@store')->name('productTypes.store');
        Route::get('product-types/{id}/edit', 'ProductTypeController@edit')->name('productTypes.edit');
        Route::post('product-types/{id}/update', 'ProductTypeController@update')->name('productTypes.update');
        Route::get('shipping-list', 'OrderController@index')->name('orders.index');
        Route::get('chang-status/{id}', 'OrderController@show')->name('changeStatus');
        Route::post('update-status/{id}', 'OrderController@update')->name('updateStatus');
        Route::get('invoice/{id}', 'OrderController@printInvoice')->name('invoice');
        Route::get('online-order-lists', 'OrderController@onlineOrderList')->name('orders.onlineOrderList');
        Route::get('add-shipping', 'OrderController@create')->name('addShipping');
        Route::post('shipping-create', 'OrderController@store')->name('orders.store');
        Route::get('/company-settings', 'CompanySettingController@show')->name('companySetting');
        Route::post('/company-settings/{setting}', 'CompanySettingController@update')->name('companySettingUpdate');
        Route::get('/parcel-report','ReportController@index')->name('parcleReport');
        Route::get('/parcel-report/genearate','ReportController@generateReport')->name('parcelShowreport');

    });
});

//
//Route::fallback(static function () {
//    return redirect('/');
//});

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;

class Order extends Model
{

    public const  PENDING = 'pending';

    public const  RECEIEVED = 'received';

    public const COLLECTING = 'collecting';

    public const DELIVERD = 'deliverd';

    public const REDELIVERD = 'redeliverd';

    public const RETURNT = 'return';

    protected $guarded = [];
    protected $with = ['productType'];


    protected  $casts = [
        'delivery_date_time'=>'datetime'
    ];

    public function getDeliveryDateAttribute( )
    {
        return (new Carbon($this->delivery_date_time))->format('Y-m-d');
    }
    public function getCollectDateAttribute( )
    {
        return (new Carbon($this->delivery_date_time))->format('Y-m-d');
    }
    public static function getNextInvoiceNumber()
    {
        // Get the last created order
        $lastOrder = self:: orderBy('created_at', 'desc')->first();

        if (!$lastOrder) {
            // We get here if there is no order at all
            // If there is no number set it to 0, which will be 1 at the end.
            $number = 0;
        } else {
            $number = explode('-', $lastOrder->tracking_number);

            $number = $number[1];
        }
        // If we have ORD000001 in the database then we only want the number
        // So the substr returns this 000001

        // Add the string in front and higher up the number.
        // the %06d part makes sure that there are always 6 numbers in the string.
        // so it adds the missing zero's when needed.

        return sprintf('%010d', (int)$number + 1);
    }


    public function productType()
    {
        return $this->belongsTo(ProductType::class, 'product_type', 'id');
    }

    public function createBy(){
        return $this->belongsTo(User::class,'created_by','id');
    }




}

app/Http/Controllers/Backend/AuthController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AuthController extends Controller
{
    public function loginProcess(Request $request)
    {
        $this->validate ($request, [
            'login' => 'required',
            'password' => 'required',
        ]);
        $login_type = filter_var ($request->input ('login'), FILTER_VALIDATE_EMAIL)
            ? 'email'
            : 'username';
        $request->merge ([
            $login_type => $request->input ('login')
        ]);
        $credentials = $request->only ($login_type, 'password');

        $credentials['status'] = 1;

        if (Auth::attempt ($credentials)) {
            notify ()->success ('Successfully login.');
            return redirect ()->route ('dashboard.index');
        }
        notify ()->error ('These credentials do not match our records.');

        return redirect ()->back ()->withInput ();
    }

    public function logout()
    {
        \auth ()->logout ();
        session()->invalidate();
        notify ()->success ('Successfully logout.');
        return redirect ()->route ('users.login');
    }
}

app/Http/Controllers/Backend/CompanySettingController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Setting;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class CompanySettingController extends Controller
{
    public function show()
    {
        $setting=Setting::first();
        return view('backend.company-setting.edit',compact('setting'));
    }


    public function update(Request $request,Setting $setting)
    {

        $this->validate($request,[
            'company_name'=>'required',
            'company_phone'=>'required|min:8|regex:/[0-9]/',
            'email'=>'required|email',
            'country'=>'required',
            'city'=>'required',
            'address'=>'required',
        ]);

            try{
                if($request->hasFile('logo')){
                   $file=$request->file('logo');
                   $random_file_name=Str::random(20).'.'.$file->getClientOriginalExtension();
                   $file->move('public/upload/logo',$random_file_name);
                $setting->update(
                    [
                        'company_name'=>$request->input('company_name'),
                        'company_phone'=>$request->input('company_phone'),
                        'email'=>$request->input('email'),
                        'country'=>$request->input('country'),
                        'city'=>$request->input('city'),
                        'address'=>$request->input('address'),
                        'logo'=>$random_file_name
                    ]
                );
                }else{
                    $setting->update(
                        [
                            'company_name'=>$request->input('company_name'),
                            'company_phone'=>$request->input('company_phone'),
                            'email'=>$request->input('email'),
                            'country'=>$request->input('country'),
                            'city'=>$request->input('city'),
                            'address'=>$request->input('address'),
                        ]
                    );
                }
                notify()->success('Setting update');
                return redirect()->back();
            } catch (ModelNotFoundException $exception){
                notify()->error('Something is went.');
               return redirect()->back();
            }

    }

}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Order;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {

        $pending_order = Order::where('status', Order::PENDING)->count();
        $delivered_order = Order::where('status', Order::DELIVERD)->count();
        $recived_order = Order::where('status', Order::RECEIEVED)->count();
        $return_order = Order::where('status', Order::RETURNT)->count();

        return view('backend.index', compact(
            'pending_order',
            'delivered_order',
            'return_order',
            'recived_order'
        ));
    }
}

app/Http/Controllers/Backend/OrderController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\OrderRequest;
use App\Models\Order;
use App\Models\ProductType;
use App\Models\ShippingType;
use Barryvdh\DomPDF\Facade as PDF;
use Dompdf\Dompdf;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Illuminate\View\View;
use Milon\Barcode\DNS1D;
use Milon\Barcode\DNS2D;

class OrderController extends Controller
{
    public function index()
    {
        $orders = Order::paginate(10);
        return view('backend.orders.index', compact('orders'));
    }


    public function create()
    {
        $data['product_types'] = ProductType::all(['id', 'name']);
        $data['shipping_types'] = ShippingType::all(['id', 'name']);

        return view('backend.orders.create', $data);
    }

    public function store(OrderRequest $request)
    {
        $tracking_number = 'BGL-' . Order::getNextInvoiceNumber();

        $data = [
            'user_id' => auth()->user()->getAuthIdentifier(),
            'sender_name' => $request->input('sender_name'),
            'sender_email'=>$request->input('sender_email'),
            'sender_phone' => $request->input('sender_phone'),
            'sender_address' => $request->input('sender_address'),
            'description'=>$request->input('details'),
            'receiver_name' => $request->input('receiver'),
            'receiver_phone' => $request->input('receiver_phone'),
            'receiver_address' => $request->input('receiver_email'),
            'receiver_email' => $request->input('receiver_email'),
            'tracking_number' => $tracking_number,
            'status' => $request->input('status'),
            'product_type' => $request->input('product_type'),
            'collection_date_time' => $request->input('collection_date'),
            'delivery_date_time' => $request->input('delivery_date_time'),
            'payment_status' => $request->input('payment_status'),
            'weight' => $request->input('weight'),
            'quantity' => $request->input('quantity'),
        ];

        try {
            Order::create($data);
            notify()->success('Order successfully created.');
            return redirect()->route('orders.index');
        } catch (\Exception $exception) {
            notify()->error('Something went wrong.');
            return redirect()->back();
        }
    }


    public function onlineOrderList()
    {
        $orders = Order::paginate(10);
        return view('backend.orders.onlineOrdersList', compact('orders'));
    }

    public function show($id)
    {
        $order = Order::findOrfail($id);
        return view('backend.orders.show', compact('order'));
    }

    public function update(Request $request, $id)
    {
        $data = [
            'status' => $request->input('status'),
            'payment_status' => $request->input('payment_status'),
            'deliver_charge' => $request->input('deliver_charge'),
            'collection_date_time'=>date($request->input('collect_date')),
            'delivery_date_time'=>date($request->input('deliver_date'))
        ];
        try {
            $order = Order::find($id);
            $order->update($data);
            notify()->success('Sucessfully update');
            return redirect()->back();
        } catch (\Exception $exception) {
           notify()->error('Something is wrong');
            return redirect()->back();
        }
    }

    public function printInvoice($id)
    {
        $order = Order::find($id);
        $pdf = PDF::loadView('backend.orders.invoice', compact('order'))->setPaper('a4', 'portrait');
        return $pdf->stream('invoice-'.$order->id);
    }


}

app/Http/Controllers/Backend/ProductTypeController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\ProductType;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class ProductTypeController extends Controller
{
    public function index()
    {
        $product_types = ProductType::paginate(10);

        return view('backend.productsType.index', ['product_types' => $product_types]);
    }

    public function create()
    {
        return view('backend.productsType.create');
    }


    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'type_of_packing' => 'required',
            'dimension' => 'required'
        ]);

        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }
        try {
            $data = [
                'name' => $request->name,
                'type_of_packing' => $request->type_of_packing,
                'dimension' => $request->dimension,
                'status' => $request->status ? '1' : '0'
            ];
            ProductType::create($data);
            notify()->success('Product Type created successfully.');

            return redirect()->route('productTypes.index');
        } catch (\Exception $exception) {
            notify()->error('Something went wrong.Please try again.');
        }
    }
    public function edit($id){
        $product_type=ProductType::findOrfail($id);
        return view('backend.productsType.edit',compact('product_type'));
    }
    public function update(Request $request,$id){
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'type_of_packing' => 'required',
            'dimension' => 'required',
        ]);
        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }
        $data = [
            'name' => $request->name,
            'type_of_packing' => $request->type_of_packing,
            'dimension' => $request->dimension,
            'status' => $request->status ? '1' : '0'
        ];
      try{
          ProductType::findOrFail($id)->update($data);
          notify()->success('Product type sucessfully update');
          return redirect()->route('productTypes.index');
      }catch (\Exception $exception){
          notify()->error('Something is wrong');
          return redirect()->back();
      }
    }
}

resources/views/backend/orders/index.blade.php
@extends('backend.Layouts.app')

@section('title') Product-Type @endsection

@section('main')
    <div class="card rounded-lg">
        <div class="card-header d-flex justify-content-between">
            <div>
                Orders
            </div>
            <div>
                <a href="{{route('addShipping')}}" class="btn btn-info rounded-lg font-weight-bold">
                    <i class="fas fa-plus"></i>
                    New Shipping
                </a>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered rounded">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Tracking</th>
                        <th scope="col">pay mode</th>
                        <th scope="col">Shipper</th>
                        <th scope="col">Receiver</th>
                        <th scope="col">Date</th>
                        <th scope="col">Employee</th>
                        <th scope="col">status</th>
                        <th>action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($orders as $key=>$order)
                        <tr>
                            <th scope="row">{{$key+1}}</th>
                            <td>{{$order->tracking_number}}</td>
                            <td>{{$order->payment_status}}</td>
                            <td>{{$order->sender_name}}</td>
                            <td>{{$order->receiver_name}}</td>
                            <td>{{ date('d-m-Y', strtotime($order->delivery_date_time))}}</td>
                            <td>{{$order->receiver_name}}</td>
                            <td>
                                <span class="badge badge-info py-2 rounded-lg px-2 display-1">{{$order->status}}</span>
                            </td>
                            <td><a href="{{route('changeStatus',$order->id)}}"><i class="fa fa-edit"></i></a></td>
                        </tr>
                    </tbody>
                    @endforeach
                </table>
            </div>
        </div>
        <div class="card-footer text-right">
            {{$orders->links()}}
        </div>
    </div>
@endsection

resources/views/backend/orders/show.blade.php
@extends('backend.Layouts.app')
@section('main')
    <div class="container">
        <form action="{{route('updateStatus',$order->id)}}" method="post">
            @csrf
            <div class="card border-0 shadow-sm rounded-lg">
                <div class="card-header d-flex justify-content-between">
                    <div>
                        <span>Order</span>
                    </div>
                    <div>
                        <a class="btn btn-warning rounded-lg d-inline-block text-white" href="{{route('orders.index')}}">Back</a>
                        <a href="{{route('invoice',$order->id)}}" class="btn btn-info rounded-lg px-5 text-uppercase">Print</a>
                        <button class="btn btn-info rounded-lg px-4 text-uppercase" type="submit">Update</button>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-9">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="card border-0 shadow-sm rounded-lg">
                                        <div class="card-header">
                                            Sender Details
                                        </div>
                                        <div class="card-body">
                                            <ul class="list-group list-unstyled">
                                                <li class="border-bottom py-1  px-2">
                                                    <span>Name :</span>
                                                    <span>{{$order->sender_name}}</span>
                                                </li>
                                                <li class="border-bottom py-1  px-2">
                                                    <span>Email :</span>
                                                    <span>{{$order->sender_email}}</span>
                                                </li>
                                                <li class="border-bottom py-1  px-2">
                                                    <span>Phone :</span>
                                                    <span>{{$order->sender_phone}}</span>
                                                </li>
                                                <li class="border-bottom py-1  px-2">
                                                    <span>Address :</span>
                                                    <span>{{$order->sender_address}}</span>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="card border-0 shadow-sm rounded-lg">
                                        <div class="card-header">
                                            Receiver Details
                                        </div>
                                        <div class="card-body">
                                            <ul class="list-group list-unstyled">
                                                <li class="border-bottom py-1  px-2">
                                                    <span>Name :</span>
                                                    <span>{{$order->receiver_name}}</span>
                                                </li>
                                                <li class="border-bottom py-1  px-2">
                                                    <span>Phone :</span>
                                                    <span>{{$order->receiver_phone}}</span>
                                                </li>
                                                <li class="border-bottom py-1  px-2">
                                                    <span>email :</span>
                                                    <span>{{$order->receiver_email}}</span>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12 pt-5">
                                    <div class="card rounded-lg border-0 shadow">
                                        <div class="card-header">
                                            <p>Product details</p>
                                        </div>
                                        <div class="card-body">
                                            <p>{{$order->description}}</p>
                                        </div>
                                        <div class="card-footer">
                                            Payment:
                                            <button type="button"
                                                    class="badge badge-info border-0 rounded-lg">{{$order->payment_status}}</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="card border-0 shadow-sm rounded-lg">
                                <div class="card-body">

                                    <div class="form-group">
                                        <label for="exampleFormControlSelect1">Status</label>
                                        <select class="form-control rounded-lg" name="status"
                                                id="exampleFormControlSelect1">
                                            <option value="pending" {{$order->status=== 'pending' ? 'selected':''}}>
                                                Pending
                                            </option>
                                            <option value="received" {{$order->status=== 'received' ? 'selected':''}}>
                                                Received
                                            </option>
                                            <option
                                                {{$order->status=== 'collecting' ? 'selected':''}} value="collecting ">
                                                Collecting
                                            </option>
                                            <option {{$order->status=== 'deliverd' ? 'selected':''}} value="deliverd">
                                                Delivered
                                            </option>
                                            <option
                                                {{$order->status=== 'redeliverd' ? 'selected':''}}  value="redeliverd">
                                                Re-Delivered
                                            </option>
                                            <option {{$order->status=== 'return' ? 'selected':''}}  value="return">
                                                Return
                                            </option>
                                        </select>
                                    </div>
                                    <div class="form-group d-flex">
                                        <div class="custom-control custom-radio mr-3">
                                            <input type="radio" id="paid" name="payment_status"
                                                   class="custom-control-input"
                                                   {{$order->payment_status==='paid' ? 'checked':''}} value="paid">
                                            <label class="custom-control-label" for="paid">Paid</label>
                                        </div>
                                        <div class="custom-control custom-radio">
                                            <input type="radio" id="cod" name="payment_status"
                                                   class="custom-control-input"
                                                   value="cod" {{$order->payment_status==='cod' ? 'checked':''}}>
                                            <label class="custom-control-label" for="cod">COD</label>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="shipping-charge">Shipping Charge</label>
                                        <input type="text" class="form-control rounded-lg" id="shipping-charge"
                                               placeholder="Shipping charge" value="{{number_format($order->deliver_charge)}}"
                                               name="deliver_charge">
                                    </div>
                                    <div class="form-group">
                                        <label for="shipping-charge">Delivery schedule</label>
                                        <input type="date" class="form-control rounded-lg" id="shipping-charge"

                                               placeholder="Shipping charge" value="{{$order->delivery_date}}"
                                               name="deliver_date">
                                    </div>
                                    <div class="form-group">
                                        <label for="shipping-charge">Collection schedule</label>
                                        <input  type="date" class="form-control rounded-lg" id="shipping-charge"
                                               placeholder="Shipping charge" value="{{$order->collect_date}}"
                                               name="collect_date">
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
@endsection